#!/usr/bin/env python3
"""A stand-in for `adb` + a phone running scrcpy-server, for end-to-end tests.

`forward` stores the local port; `shell ... app_process ...` then plays the
role of the scrcpy server: it listens on that port and speaks the real
protocol with an H.264 stream generated by libx264. Received control messages
are appended to $FAKE_ADB_DIR/control.bin.
"""

import os
import socket
import struct
import sys
import threading
import time

STATE = os.environ.get("FAKE_ADB_DIR", "")


def port_file():
    return os.path.join(STATE, "port")


def main(argv):
    if argv[:1] == ["-s"]:
        argv = argv[2:]
    cmd = argv[0]
    if cmd == "devices":
        print("List of devices attached")
        if not os.path.exists(os.path.join(STATE, "nodevice")):
            print("FAKE123        device usb:1-1 product:x model:Fake_Phone device:fake")
    elif cmd == "push":
        pass
    elif cmd == "forward":
        if argv[1] != "--remove":
            with open(port_file(), "w") as f:
                f.write(argv[1].split(":")[1])
    elif cmd == "shell":
        rest = " ".join(argv[1:])
        if "dumpsys window" in rest:
            fg = "com.test.game"
            if os.path.exists(os.path.join(STATE, "fg")):
                fg = open(os.path.join(STATE, "fg")).read().strip()
            print("  mCurrentFocus=Window{1a2b u0 %s/%s.MainActivity}" % (fg, fg))
        elif "app_process" in rest:
            serve("audio=true" in rest)
        elif "getprop" in rest:
            print("34")
    return 0


def encode_frames(width, height, count, color_shift):
    import av
    import numpy as np
    codec = av.CodecContext.create("libx264", "w")
    codec.width, codec.height = width, height
    codec.pix_fmt = "yuv420p"
    codec.time_base = __import__("fractions").Fraction(1, 60)
    codec.options = {"tune": "zerolatency", "preset": "ultrafast"}
    packets = []
    for i in range(count):
        img = np.zeros((height, width, 3), dtype=np.uint8)
        img[:, :, 0] = (i * 8 + color_shift) % 256
        img[: height // 2, : width // 2, 1] = 255  # green top-left quadrant
        frame = av.VideoFrame.from_ndarray(img, format="rgb24")
        frame.pts = i
        packets += [(bytes(p), p.is_keyframe) for p in codec.encode(frame)]
    packets += [(bytes(p), p.is_keyframe) for p in codec.encode(None)]
    return packets


def serve(with_audio):
    counter = os.path.join(STATE, "sessions")
    n = int(open(counter).read()) + 1 if os.path.exists(counter) else 1
    with open(counter, "w") as f:
        f.write(str(n))
    # Simulate a pulled cable during the first session if asked to.
    cut_file = os.path.join(STATE, "disconnect_after")
    cut_at = time.monotonic() + float(open(cut_file).read()) if n == 1 and os.path.exists(cut_file) else None
    for _ in range(100):
        if os.path.exists(port_file()):
            break
        time.sleep(0.05)
    port = int(open(port_file()).read())
    srv = socket.socket()
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    time.sleep(0.3)  # let the client hit "connection refused" once, like a slow phone
    srv.bind(("127.0.0.1", port))
    srv.listen(3)

    video, _ = srv.accept()
    video.sendall(b"\0")
    audio = srv.accept()[0] if with_audio else None
    control, _ = srv.accept()

    threading.Thread(target=read_control, args=(control,), daemon=True).start()

    name = b"Fake Phone".ljust(64, b"\0")
    video.sendall(name)
    video.sendall(struct.pack(">III", 0x68323634, 640, 360))
    if audio:
        audio.sendall(struct.pack(">I", 0x6F707573))  # "opus"
        threading.Thread(target=send_audio, args=(audio,), daemon=True).start()

    t0 = time.monotonic()

    def send(pkts):
        for data, key in pkts:
            if cut_at and time.monotonic() > cut_at:
                raise OSError("cable pulled")
            # pts in microseconds from the capture clock, like the real server
            pts = int((time.monotonic() - t0) * 1e6)
            flags = (1 << 62) if key else 0
            video.sendall(struct.pack(">QI", flags | pts, len(data)) + data)
            time.sleep(1 / 60)

    try:
        # A config packet (empty SPS placeholder is not valid, so send a real
        # keyframe stream; the first packet carries SPS/PPS inline).
        send(encode_frames(640, 360, 90, 0))      # landscape
        send(encode_frames(360, 640, 60, 100))    # "rotated" to portrait
        send(encode_frames(640, 360, 600, 0))     # back to landscape, keep streaming
    except OSError:
        pass
    for sock in (video, audio, control):
        if sock:
            sock.close()


def opus_packets(seconds=1.0):
    """(OpusHead config, [20 ms packets]) of a 440 Hz tone, like the phone sends."""
    import av
    import numpy as np
    enc = av.CodecContext.create("libopus", "w")
    enc.sample_rate, enc.layout, enc.format, enc.bit_rate = 48000, "stereo", "s16", 128000
    n = int(48000 * seconds)
    tone = (np.sin(2 * np.pi * 440 * np.arange(n) / 48000) * 8000).astype(np.int16)
    packets = []
    for i in range(0, n, 960):
        chunk = np.repeat(tone[i:i + 960][None, :], 2, axis=0).T.reshape(1, -1)
        frame = av.AudioFrame.from_ndarray(chunk, format="s16", layout="stereo")
        frame.sample_rate, frame.pts = 48000, i
        packets += [bytes(p) for p in enc.encode(frame)]
    return bytes(enc.extradata), packets


def send_audio(sock):
    head, packets = opus_packets()
    try:
        sock.sendall(struct.pack(">QI", 1 << 63, len(head)) + head)
        while True:
            for p in packets:
                sock.sendall(struct.pack(">QI", 0, len(p)) + p)
                time.sleep(0.02)
    except OSError:
        pass


def read_control(sock):
    with open(os.path.join(STATE, "control.bin"), "ab") as f:
        while True:
            data = sock.recv(65536)
            if not data:
                break
            f.write(data)
            f.flush()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
